---
abstract: 'Look up country by IP address'
author:
  - 'Randy Kobes <r.kobes@uwinnipeg.ca>'
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Apache-GeoIP
no_index:
  directory:
    - t
    - inc
resources:
  repository: https://github.com/briandfoy/Apache-GeoIP
version: 1.99_01
